server:
  port: 8081


spring:
  #profiles:
  #    # 激活application-common.yml配置文件
  #    active: common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///dormitories?characterEncoding=UTF-8
    username: root
    password: 7930668bf87e3980
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache
    poolPreparedStatements: true
    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    filters: stat,wall,log4j,config
    #指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  # 配置默认的用户名和密码还有用户角色
  security:
    user:
      name: user
      password: 123456
      roles: user


logging:
  level:
    #    启动时info日志级别以上不会输出信息，默认info
    #    root: warn
    com.gdpi.mapper: trace
  pattern:
    console: '%p%m%n'


mybatis-plus:
  mapper-locations:
    - com/gdpi/mapper/xml/*
  type-aliases-package: com.gdpi.entity
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射，默认值：true
    map-underscore-to-camel-case: true


jwt:
  secret: com.gdpi
  expiration: 8640000000



dormitories:
  loginUrl: /login
  imgUrl: /login/image
  menuListUrl: /menuList
  icon: /my/icon

